ex3:
	flex ex3.l
	gcc -o ex3.exe lex.yy.c -lfl

ex12: 
	flex ex12.l
	gcc -o ex12.exe lex.yy.c -lfl

ex13: 
	flex ex13.l
	gcc -o ex13.exe lex.yy.c -lfl

ex14:
	flex ex14.l
	gcc -o ex14.exe lex.yy.c -lfl

ex15:
	flex ex15.l
	gcc -o ex15.exe lex.yy.c -lfl

clean:
	rm *.exe