par.exe : y.tab.o lex.yy.o
	gcc -o par.exe y.tab.o lex.yy.o -lfl

y.tab.o : y.tab.c
	gcc -c y.tab.c

lex.yy.o : lex.yy.c
	gcc -c lex.yy.c

y.tab.c y.tab.h : par.y
	yacc -d par.y

lex.yy.c : par.l y.tab.h 
	flex par.l